import { StyleSheet } from "react-native";
import { colors } from "../constants/colors";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 10,
    justifyContent: "space-evenly",
    backgroundColor: "white",
  },
  text: {
    fontSize: 24,
    color: colors.primary,
    textAlign: "center",
    marginBottom: 30,
    fontFamily: "Raleway-Bold",
  },
  gender: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    padding: 10,
    fontFamily: "Raleway-Bold",
  },
  inputContainer: {
    padding: 24,
    borderRadius: 12,
    backgroundColor: colors.background,
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 10,
    margin: 10,
  },
  inputWrapper: {
    flex: 1,
    backgroundColor: colors.background,
    margin: 8,
    borderRadius: 8,
    alignItems: "center",
    height: 150,
    justifyContent: "center",
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  label: {
    fontSize: 16,
    marginBottom: 8,
    color: colors.textPrimary,
    fontFamily: "Raleway-Medium",
  },
  input: {
    padding: 6,
    borderBottomWidth: 2,
    borderColor: colors.primary,
    textAlign: "center",
    marginTop: 8,
    fontSize: 22,
    color: colors.textPrimary,
    maxWidth: 60,
    alignSelf: "center",
    fontFamily: "Raleway-Medium",
  },
  resultContainer: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "center",
  },
  resultText: {
    fontSize: 24,
    color: colors.backgroundLight,
    fontFamily: "Raleway-Bold",
  },
  customButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 28,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 6,
    elevation: 5,
  },
  buttonText: {
    fontSize: 16,
    textAlign: "center",
    color: colors.primaryDark,
    fontFamily: "Raleway-SemiBold",
  },
  subheader: {
    fontSize: 16,
    marginBottom: 5,
    color: colors.textPrimary,
    fontFamily: "Raleway-Bold",
  },
  classification: {
    fontSize: 14,
    color: colors.textPrimary,
    textAlign: "justify",
    marginTop: 4,
    lineHeight: 17,
    fontFamily: "Raleway-Regular",
  },
  againButton: {
    margin: 10,
    paddingVertical: 6,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "center",
    fontFamily: "Raleway-Medium",
  },
  factorsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: 10,
  },
});

export default styles;
